openapi: 3.0.2
info:
  title: Category RESTful API
  description: API Spec for Category RESTful API
  version: "1.0"
servers:
  - url: http://localhost:3000/api
paths:
  /categories:
    get:
      tags:
        - Category API
      security:
        - categoryAuth: []
      description: List all categories
      summary: List all categories
      responses:
        "200":
          description: Success get all Categories
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/categoryArray"
    post:
      tags:
        - Category API
      security:
        - categoryAuth: []
      description: Create new category
      summary: Create new category
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/categoryName"
      responses:
        "200":
          description: Success create category
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/categoryArray"
  /category/{categoryId}:
    get:
      tags:
        - Category API
      security:
        - categoryAuth: []
      description: Get category by Id
      summary: Get category by Id
      parameters:
        - $ref: "#/components/parameters/categoryId"
      responses:
        "200":
          description: Success get category by Id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/categoryObject"
    put:
      tags:
        - Category API
      security:
        - categoryAuth: []
      description: Update category by Id
      summary: Update category by Id
      parameters:
        - $ref: "#/components/parameters/categoryId"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/categoryName"
      responses:
        "200":
          description: Success update category
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/categoryObject"
    delete:
      tags:
        - Category API
      security:
        - categoryAuth: []
      description: Delete category by Id
      summary: Delete category by Id
      parameters:
        - $ref: "#/components/parameters/categoryId"
      responses:
        "200":
          description: Success delete category
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/responseCode"
components:
  securitySchemes:
    categoryAuth:
      type: apiKey
      in: header
      name: X-API-KEY
      description: Authentication for Category API
  schemas:
    responseCode:
      type: object
      properties:
        code:
          type: number
        status:
          type: string
    categoryName:
      type: object
      properties:
        name:
          type: string
    categoryArray:
      type: object
      properties:
        code:
          type: number
        status:
          type: string
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: number
              name:
                type: string
    categoryObject:
      type: object
      properties:
        code:
          type: number
        status:
          type: string
        data:
          type: object
          properties:
            id:
              type: number
            name:
              type: string
  parameters:
    categoryId:
      name: categoryId
      in: path
      description: Category Id
      required: true
      schema:
        type: number
